### ISSUE TITLE
Dev builds aren't updated anymore

### ISSUE THREAD

**Issue by cmfcmf** [craigh/ExtensionLibrary#76]
> @cmfcmf I don't think zikula.org is updating the development builds any longer.
--  @craigh

**Comment by craigh** [comment]
![screen shot 2015-04-25 at 12 06 14 pm](https://cloud.githubusercontent.com/assets/350048/7333590/84b74564-eb43-11e4-879c-27d540432439.png)

As of this posting, the current build is 561 - so very behind for some reason...
