### ISSUE TITLE
Seperate core release process from this module

### ISSUE THREAD

**Issue by cmfcmf** [craigh/ExtensionLibrary#81]

**Comment by cmfcmf** [comment]
All the necessary bits have been copied to a functional second module at https://github.com/cmfcmf/CoreManagerModule. 
TODO:
- remove all core management stuff from the ExtensionLibrary
- add the CoreManager module to the EL requirements
- use the api function of the CoreManager module to fetch core versions to filter extensions after

**Comment by cmfcmf** [comment]
This is done.

**Comment by craigh** [comment]
:+1:
