### ISSUE TITLE
Fatal error: Uncaught exception 'ReflectionException' with message 'Class Zikula\Module\CoreManagerModule\Api\ReleasesV1Api does not exist'

### ISSUE THREAD

**Issue by ghost** [craigh/ExtensionLibrary#97]
Hello Developers,

I wanted to test this module times and when activating I get these error messages displayed.

`Fatal error: Uncaught exception 'ReflectionException' with message 'Class Zikula\Module\CoreManagerModule\Api\ReleasesV1Api does not exist' in /xxxxxxxxxxxxxxxxxx/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php:38 Stack trace: #0 /xxxxxxxxxxxxxxxxxxxx/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(38): ReflectionParameter->getClass() #1 /xxxxxxxxxxxxxxx/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentsValidator.php(20): Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator->validate(Object(ReflectionParameter), NULL) #2 /xxxxxxxxxxxxxxx/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-definition-validator/DefinitionArgumentsValidator.php(37): Matthias\SymfonyServiceDefinitionValidator\ArgumentsValidator->validate(Object(ReflectionMethod), Array) #3 /xxxxxxxxxxx/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-defi in /www/htdocs/w0103f82/zikula.wpzweinull.ch/src/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php on line 38`

I use Zikula 1.4.6 and PHP 5.6.

Can you see this again. Thanks in advance.

**Comment by craigh** [comment]
This module is not designed for end users.
